# Generated by Django 4.1.13 on 2023-12-04 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consumption',
            name='user',
        ),
    ]
